#!/bin/bash
NODE_CONF_DIR=/etc/cluster/nodes
required_files="eth0-ip eth0-mac"
clustertooldir=/usr/libexec/cluster/

for node in `ls $NODE_CONF_DIR` ; do
 for file in $required_files ; do
  if [ ! -f $NODE_CONF_DIR/$node/$file ] ; then
   echo "Required file $NODE_CONF_DIR/$node/$file not found"
   exit 1
  fi
 done
 # Make new nodes reinstall (identify new nodes by not having premade ssh keys)
 if [ ! -d $NODE_CONF_DIR/$node/ssh ] ; then
  touch $NODE_CONF_DIR/$node/reinstall
 fi

done

$clustertooldir/check-ssh-keys
$clustertooldir/update-dhcpd-conf
$clustertooldir/update-named-conf
$clustertooldir/update-machines
$clustertooldir/link-package-file
$clustertooldir/distribute-files

echo "Node added and services restarted"

