#!/bin/bash
SCRIPT=`basename $0`
CURRDIR=`dirname $0`
CLUSTER_SETUP_DIR="`dirname $0?`/../../rootfs/"
CLUSTER_CONF_DIR=$CURRDIR/../conf/
echo "$SCRIPT: Creating cluster configuration under /etc/cluster"
cp -r $CLUSTER_SETUP_DIR/etc/cluster /etc/
if [ $? -ne 0 ] ; then
 echo "Error copying the config files" >&2
 exit 1
fi

echo "$SCRIPT: Copying over network infomation to cluster directory"
cp $CLUSTER_CONF_DIR/cluster.conf $CLUSTER_CONF_DIR/default-packages /etc/cluster/conf

echo "$SCRIPT: Done" 
