#!/bin/bash
if [ -d "/tmp/slurm-$SLURM_JOBID" ] ; then
 # Check if there are locks left
 lock=`ls /tmp/slurm-$SLURM_JOBID/slurmlock.* 2>/dev/null |head -n1`
 if [ "x$lock" != "x" ] ; then
  if [ -f "$lock" ] ; then
   #if there are, remove one of them
   rm -f "$lock"
   #if no more locks are left, remove the directory
   lock2=`ls /tmp/slurm-$SLURM_JOBID/slurmlock.* 2>/dev/null |head -n1`
   if [ "x$lock2" == "x" ] ; then
    rm -rf /tmp/slurm-$SLURM_JOBID
   fi
  fi
 else
  rm -rf /tmp/slurm-$SLURM_JOBID
 fi
fi

